### ISSUE TITLE
Not working on github actions

### ISSUE THREAD

**Issue by akothari-godaddy** [godaddy/tartufo-action#7]
When I run tartufo --config ./tartofu.toml scan-local-repo --branch dev . on my laptop, the tools run fine detecting no secrets in my repo but on github actions https://github.com/gdcorp-domains/fulfillment-domain-capture-api the tools sends a huge list of secrets detected.

**Comment by smimani-godaddy** [comment]
Hi. Your file is named incorrectly. https://github.com/gdcorp-domains/fulfillment-domain-capture-api/blob/dev/tartofu.toml
Since you specify that in the cli, tartufo uses it but since the action doesn't let you specify a config file but looks for `tartufo.toml` or `pyproject.toml` it cannot use that file.
